title: Composers
pages:
  num: zero
  template: composer
files: false
options:
  template: false
fields:
  title:
    label: Title
    type: text
  advertisements:
    extends: pick_many_advertisements
    limit: 3
    help: Pick 3 advertisements
