title: Composer
pages: false
files:
  size: 3000000
  width: 2000
  height: 2000
  fields:
    focus:
      label: Specify the focus point
      type: focus
      help: If this image gets cropped, it will crop towards this focus point
fields:
  title:
    label: Full Name
    type: text
  location:
    label: Location
    type: text
    placeholder: e.g. New York, New York
  photo:
    label: Photo
    type: image
  bio:
    label: Bio
    type: textarea
  links:
    label: Links
    type: structure
    style: table
    fields:
      name:
        label: Name
        type: text
        placeholder: e.g. Website or Twitter
      url:
        label: URL
        type: url
