title: Site
pages:
  template: default
fields:
  title:
    label: Website Title
    type: text
  event_start_date:
    extends: date
    label: Convention Start Date
    width: 1/2
  event_end_date:
    extends: date
    label: Convention End Date
    width: 1/2
  event_location:
    label: Location
    type: text
  cvent_registration_url:
    label: Cvent Registration URL
    type: url
    required: true
  registration_cta_text:
    label: Registration CTA Text
    type: text
    help: This register CTA found on the bottom of each page.
  line:
    type: line
